apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
spec:
  selector:
    matchLabels:
      app: myspringbootapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myspringbootapp
    spec:
      containers:
      - name: myspringbootapp
        image: mrace17/mydemoapplication:latest
        # jenkins job name  mydemoapplication
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9099
