apiVersion: v1
kind: Service
metadata:
  name: myservice
  label:
    app: myspringbootapp
spec:
  type: NodePort
  selector:
    app: myspringbootapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30036
